theme: jekyll-theme-minimal
name: Welcome to the course site for CMS.S62!
description: This is the site for Digital Humanities II: Data, Archives, Interfaces, a special subject being taught at MIT during the spring of 2018.
